language: c
sudo: required
install:
  - brew upgrade gcc
  - brew install homebrew/science/openblas
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.04 EXTRA_DEPS="oasis" INSTALL=false
os:
  - osx
